/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct two_int {
	int a1;
	int a2;
};
typedef struct two_int two_int;

#define CALC_PROG 0x31111111
#define CALC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define addition 1
extern  int * addition_1(two_int *, CLIENT *);
extern  int * addition_1_svc(two_int *, struct svc_req *);
#define subtraction 2
extern  int * subtraction_1(two_int *, CLIENT *);
extern  int * subtraction_1_svc(two_int *, struct svc_req *);
#define multiplication 3
extern  int * multiplication_1(two_int *, CLIENT *);
extern  int * multiplication_1_svc(two_int *, struct svc_req *);
#define division 4
extern  int * division_1(two_int *, CLIENT *);
extern  int * division_1_svc(two_int *, struct svc_req *);
#define power 5
extern  int * power_1(two_int *, CLIENT *);
extern  int * power_1_svc(two_int *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define addition 1
extern  int * addition_1();
extern  int * addition_1_svc();
#define subtraction 2
extern  int * subtraction_1();
extern  int * subtraction_1_svc();
#define multiplication 3
extern  int * multiplication_1();
extern  int * multiplication_1_svc();
#define division 4
extern  int * division_1();
extern  int * division_1_svc();
#define power 5
extern  int * power_1();
extern  int * power_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_two_int (XDR *, two_int*);

#else /* K&R C */
extern bool_t xdr_two_int ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
